/**
 * Generates themes/King-color-theme.json from scripts/palette.mjs.
 *
 * The theme JSON is a build artifact — edit the palette, not the JSON, then run
 * `npm run build`. Keeping the colors in one place is what makes the contrast
 * guarantee in `check-contrast.mjs` meaningful.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { accent, alpha, ansi, bg, brackets, fg, git, status, syntax } from './palette.mjs';

const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'themes', 'King-color-theme.json');

const colors = {
  // ---- Base ----------------------------------------------------------------
  focusBorder: accent.purple,
  foreground: fg.chrome,
  disabledForeground: fg.subtle,
  descriptionForeground: fg.muted,
  errorForeground: status.error,
  'widget.border': alpha.hairlineStrong,
  'widget.shadow': alpha.shadow,
  'selection.background': alpha.selection,
  'icon.foreground': fg.muted,
  'sash.hoverBorder': accent.purple,

  // ---- Text (markdown preview, welcome page) -------------------------------
  'textBlockQuote.background': bg.deep,
  'textBlockQuote.border': accent.purple,
  'textCodeBlock.background': bg.deep,
  'textLink.activeForeground': accent.gold,
  'textLink.foreground': syntax.cyan,
  'textPreformat.foreground': syntax.gold,
  'textSeparator.foreground': alpha.hairlineStrong,

  // ---- Buttons -------------------------------------------------------------
  'button.background': accent.gold,
  'button.foreground': bg.deepest,
  'button.hoverBackground': '#F7D670',
  'button.secondaryBackground': bg.raisedHigh,
  'button.secondaryForeground': fg.primary,
  'button.secondaryHoverBackground': '#3F3159',
  'checkbox.background': bg.raised,
  'checkbox.border': alpha.hairlineStrong,
  'checkbox.foreground': fg.primary,

  // ---- Dropdowns & inputs --------------------------------------------------
  'dropdown.background': bg.raised,
  'dropdown.listBackground': bg.raised,
  'dropdown.border': alpha.hairlineStrong,
  'dropdown.foreground': fg.primary,
  'input.background': bg.raised,
  'input.border': alpha.hairlineStrong,
  'input.foreground': fg.primary,
  'input.placeholderForeground': fg.subtle,
  'inputOption.activeBackground': `${accent.purple}33`,
  'inputOption.activeBorder': accent.purple,
  'inputOption.activeForeground': fg.primary,
  'inputValidation.errorBackground': '#3D1A22',
  'inputValidation.errorBorder': status.error,
  'inputValidation.errorForeground': fg.primary,
  'inputValidation.infoBackground': '#1A2740',
  'inputValidation.infoBorder': status.info,
  'inputValidation.infoForeground': fg.primary,
  'inputValidation.warningBackground': '#3A3016',
  'inputValidation.warningBorder': status.warning,
  'inputValidation.warningForeground': fg.primary,

  // ---- Scrollbars & badges -------------------------------------------------
  'scrollbar.shadow': alpha.shadow,
  'scrollbarSlider.background': alpha.scrollbar,
  'scrollbarSlider.hoverBackground': alpha.scrollbarHover,
  'scrollbarSlider.activeBackground': alpha.scrollbarActive,
  'badge.background': accent.gold,
  'badge.foreground': bg.deepest,
  'progressBar.background': accent.gold,

  // ---- Lists & trees -------------------------------------------------------
  'list.activeSelectionBackground': accent.purpleDeep,
  'list.activeSelectionForeground': '#FFFFFF',
  'list.activeSelectionIconForeground': '#FFFFFF',
  'list.inactiveSelectionBackground': bg.raisedHigh,
  'list.inactiveSelectionForeground': fg.primary,
  'list.hoverBackground': alpha.hover,
  'list.hoverForeground': fg.primary,
  'list.focusBackground': bg.raisedHigh,
  'list.focusForeground': fg.primary,
  'list.focusOutline': accent.purple,
  'list.highlightForeground': accent.gold,
  'list.focusHighlightForeground': accent.gold,
  'list.errorForeground': status.error,
  'list.warningForeground': status.warning,
  'list.dropBackground': `${accent.purple}26`,
  'listFilterWidget.background': bg.raised,
  'listFilterWidget.outline': accent.gold,
  'listFilterWidget.noMatchesOutline': status.error,
  'tree.indentGuidesStroke': alpha.hairlineStrong,
  'tree.inactiveIndentGuidesStroke': alpha.hairline,

  // ---- Activity bar --------------------------------------------------------
  'activityBar.background': bg.deepest,
  'activityBar.foreground': accent.gold,
  'activityBar.inactiveForeground': fg.subtle,
  'activityBar.border': alpha.hairline,
  'activityBar.activeBorder': accent.gold,
  'activityBar.activeBackground': `${accent.gold}14`,
  'activityBarBadge.background': accent.gold,
  'activityBarBadge.foreground': bg.deepest,

  // ---- Side bar ------------------------------------------------------------
  'sideBar.background': bg.deep,
  'sideBar.foreground': fg.chrome,
  'sideBar.border': alpha.hairline,
  'sideBarTitle.foreground': fg.muted,
  'sideBarSectionHeader.background': bg.deep,
  'sideBarSectionHeader.foreground': fg.chrome,
  'sideBarSectionHeader.border': alpha.hairline,

  // ---- Editor groups & tabs ------------------------------------------------
  'editorGroup.border': alpha.hairlineStrong,
  'editorGroup.dropBackground': `${accent.purple}26`,
  'editorGroupHeader.tabsBackground': bg.deep,
  'editorGroupHeader.tabsBorder': alpha.hairline,
  'editorGroupHeader.noTabsBackground': bg.deep,
  'tab.activeBackground': bg.editor,
  'tab.activeForeground': fg.primary,
  'tab.activeBorderTop': accent.gold,
  'tab.activeBorder': bg.editor,
  'tab.inactiveBackground': bg.deep,
  'tab.inactiveForeground': fg.subtle,
  'tab.hoverBackground': bg.raised,
  'tab.hoverForeground': fg.primary,
  'tab.border': alpha.hairline,
  'tab.unfocusedActiveForeground': fg.muted,
  'tab.unfocusedInactiveForeground': fg.subtle,
  'tab.unfocusedActiveBorderTop': alpha.hairlineStrong,
  'tab.lastPinnedBorder': accent.purple,
  'editorPane.background': bg.editor,

  // ---- Editor core ---------------------------------------------------------
  'editor.background': bg.editor,
  'editor.foreground': fg.primary,
  'editorLineNumber.foreground': fg.subtle,
  'editorLineNumber.activeForeground': accent.gold,
  'editorCursor.foreground': accent.gold,
  'editorCursor.background': bg.editor,
  'editor.selectionBackground': alpha.selection,
  'editor.selectionForeground': fg.primary,
  'editor.inactiveSelectionBackground': alpha.selectionInactive,
  'editor.selectionHighlightBackground': alpha.wordHighlight,
  'editor.selectionHighlightBorder': alpha.hairlineStrong,
  'editor.wordHighlightBackground': alpha.wordHighlight,
  'editor.wordHighlightStrongBackground': alpha.wordHighlightStrong,
  'editor.findMatchBackground': alpha.findMatch,
  'editor.findMatchHighlightBackground': alpha.findMatchHighlight,
  'editor.findRangeHighlightBackground': alpha.hairline,
  'editor.hoverHighlightBackground': `${accent.purple}26`,
  'editor.lineHighlightBackground': alpha.lineHighlight,
  'editor.lineHighlightBorder': '#00000000',
  'editor.rangeHighlightBackground': alpha.hairline,
  'editorLink.activeForeground': accent.gold,
  'editorWhitespace.foreground': '#FFFFFF1A',
  'editorIndentGuide.background1': alpha.hairline,
  'editorIndentGuide.activeBackground1': alpha.hairlineStrong,
  // Deprecated in favour of the numbered keys above, but still honoured — kept so
  // indent guides are themed on the 1.70 baseline the manifest declares.
  'editorIndentGuide.background': alpha.hairline,
  'editorIndentGuide.activeBackground': alpha.hairlineStrong,
  'editorRuler.foreground': alpha.hairline,
  'editorCodeLens.foreground': fg.subtle,
  'editorLightBulb.foreground': accent.gold,
  'editorLightBulbAutoFix.foreground': syntax.cyan,
  'editorBracketMatch.background': `${accent.gold}26`,
  'editorBracketMatch.border': accent.gold,
  'editorOverviewRuler.border': '#00000000',
  'editorOverviewRuler.findMatchForeground': `${accent.gold}99`,
  'editorOverviewRuler.rangeHighlightForeground': `${accent.purple}99`,
  'editorOverviewRuler.selectionHighlightForeground': `${accent.purple}66`,
  'editorOverviewRuler.wordHighlightForeground': `${accent.purple}66`,
  'editorOverviewRuler.wordHighlightStrongForeground': `${accent.gold}66`,
  'editorOverviewRuler.modifiedForeground': git.modified,
  'editorOverviewRuler.addedForeground': git.added,
  'editorOverviewRuler.deletedForeground': git.deleted,
  'editorOverviewRuler.errorForeground': status.error,
  'editorOverviewRuler.warningForeground': status.warning,
  'editorOverviewRuler.infoForeground': status.info,

  // ---- Diagnostics ---------------------------------------------------------
  'editorError.foreground': status.error,
  'editorWarning.foreground': status.warning,
  'editorInfo.foreground': status.info,
  'editorHint.foreground': fg.subtle,
  'editorGutter.background': bg.editor,
  'editorGutter.modifiedBackground': git.modified,
  'editorGutter.addedBackground': git.added,
  'editorGutter.deletedBackground': git.deleted,
  'editorGutter.foldingControlForeground': fg.muted,
  'problemsErrorIcon.foreground': status.error,
  'problemsWarningIcon.foreground': status.warning,
  'problemsInfoIcon.foreground': status.info,

  // ---- Brackets ------------------------------------------------------------
  ...Object.fromEntries(brackets.map((c, i) => [`editorBracketHighlight.foreground${i + 1}`, c])),
  'editorBracketHighlight.unexpectedBracket.foreground': status.error,
  'editorBracketPairGuide.activeBackground1': `${accent.gold}66`,
  'editorBracketPairGuide.background1': alpha.hairline,

  // ---- Inlay hints, sticky scroll, folding ---------------------------------
  'editorInlayHint.background': `${accent.purple}1F`,
  'editorInlayHint.foreground': fg.muted,
  'editorInlayHint.typeBackground': `${accent.purple}1F`,
  'editorInlayHint.typeForeground': syntax.gold,
  'editorInlayHint.parameterBackground': `${accent.purple}1F`,
  'editorInlayHint.parameterForeground': syntax.peach,
  'editorStickyScroll.background': bg.deep,
  'editorStickyScrollHover.background': bg.raised,

  // ---- Widgets -------------------------------------------------------------
  'editorWidget.background': bg.raised,
  'editorWidget.foreground': fg.primary,
  'editorWidget.border': alpha.hairlineStrong,
  'editorSuggestWidget.background': bg.raised,
  'editorSuggestWidget.border': alpha.hairlineStrong,
  'editorSuggestWidget.foreground': fg.primary,
  'editorSuggestWidget.highlightForeground': accent.gold,
  'editorSuggestWidget.focusHighlightForeground': accent.gold,
  'editorSuggestWidget.selectedBackground': accent.purpleDeep,
  'editorSuggestWidget.selectedForeground': '#FFFFFF',
  'editorHoverWidget.background': bg.raised,
  'editorHoverWidget.foreground': fg.primary,
  'editorHoverWidget.border': alpha.hairlineStrong,
  'editorGhostText.foreground': fg.subtle,
  'peekView.border': accent.purple,
  'peekViewEditor.background': bg.deep,
  'peekViewEditor.matchHighlightBackground': `${accent.gold}59`,
  'peekViewEditorGutter.background': bg.deep,
  'peekViewResult.background': bg.deep,
  'peekViewResult.fileForeground': fg.primary,
  'peekViewResult.lineForeground': fg.muted,
  'peekViewResult.matchHighlightBackground': `${accent.gold}59`,
  'peekViewResult.selectionBackground': accent.purpleDeep,
  'peekViewResult.selectionForeground': '#FFFFFF',
  'peekViewTitle.background': bg.raised,
  'peekViewTitleDescription.foreground': fg.muted,
  'peekViewTitleLabel.foreground': fg.primary,

  // ---- Diff editor ---------------------------------------------------------
  'diffEditor.insertedTextBackground': alpha.diffInserted,
  'diffEditor.removedTextBackground': alpha.diffRemoved,
  'diffEditor.insertedLineBackground': alpha.diffInserted,
  'diffEditor.removedLineBackground': alpha.diffRemoved,
  'diffEditorGutter.insertedLineBackground': alpha.diffInsertedGutter,
  'diffEditorGutter.removedLineBackground': alpha.diffRemovedGutter,
  'diffEditor.diagonalFill': alpha.hairlineStrong,

  // ---- Merge conflicts -----------------------------------------------------
  'merge.currentHeaderBackground': `${syntax.sage}40`,
  'merge.currentContentBackground': `${syntax.sage}1F`,
  'merge.incomingHeaderBackground': `${syntax.cyan}40`,
  'merge.incomingContentBackground': `${syntax.cyan}1F`,
  'merge.commonHeaderBackground': `${fg.subtle}40`,
  'merge.commonContentBackground': `${fg.subtle}1F`,
  'merge.border': alpha.hairlineStrong,

  // ---- Panel & terminal ----------------------------------------------------
  'panel.background': bg.deep,
  'panel.border': alpha.hairlineStrong,
  'panelTitle.activeBorder': accent.gold,
  'panelTitle.activeForeground': fg.primary,
  'panelTitle.inactiveForeground': fg.subtle,
  'panelSection.border': alpha.hairlineStrong,
  'panelSectionHeader.background': bg.deep,
  'panelSectionHeader.foreground': fg.chrome,
  'terminal.background': bg.deep,
  'terminal.foreground': fg.primary,
  'terminal.border': alpha.hairlineStrong,
  'terminal.selectionBackground': alpha.selection,
  'terminalCursor.foreground': accent.gold,
  'terminalCursor.background': bg.deep,
  'terminal.ansiBlack': ansi.black,
  'terminal.ansiBrightBlack': ansi.brightBlack,
  'terminal.ansiRed': ansi.red,
  'terminal.ansiBrightRed': ansi.brightRed,
  'terminal.ansiGreen': ansi.green,
  'terminal.ansiBrightGreen': ansi.brightGreen,
  'terminal.ansiYellow': ansi.yellow,
  'terminal.ansiBrightYellow': ansi.brightYellow,
  'terminal.ansiBlue': ansi.blue,
  'terminal.ansiBrightBlue': ansi.brightBlue,
  'terminal.ansiMagenta': ansi.magenta,
  'terminal.ansiBrightMagenta': ansi.brightMagenta,
  'terminal.ansiCyan': ansi.cyan,
  'terminal.ansiBrightCyan': ansi.brightCyan,
  'terminal.ansiWhite': ansi.white,
  'terminal.ansiBrightWhite': ansi.brightWhite,

  // ---- Status bar ----------------------------------------------------------
  'statusBar.background': bg.deepest,
  'statusBar.foreground': fg.chrome,
  'statusBar.border': alpha.hairline,
  'statusBar.debuggingBackground': accent.gold,
  'statusBar.debuggingForeground': bg.deepest,
  'statusBar.debuggingBorder': accent.gold,
  'statusBar.noFolderBackground': bg.deepest,
  'statusBar.noFolderForeground': fg.chrome,
  'statusBarItem.hoverBackground': alpha.hover,
  'statusBarItem.activeBackground': alpha.hairlineStrong,
  'statusBarItem.prominentBackground': accent.purpleDeep,
  'statusBarItem.prominentForeground': '#FFFFFF',
  'statusBarItem.prominentHoverBackground': accent.purple,
  'statusBarItem.remoteBackground': accent.purpleDeep,
  'statusBarItem.remoteForeground': '#FFFFFF',
  'statusBarItem.errorBackground': '#7A2430',
  'statusBarItem.errorForeground': '#FFFFFF',
  'statusBarItem.warningBackground': '#6B5310',
  'statusBarItem.warningForeground': '#FFFFFF',

  // ---- Title bar & menus ---------------------------------------------------
  'titleBar.activeBackground': bg.deepest,
  'titleBar.activeForeground': fg.chrome,
  'titleBar.inactiveBackground': bg.deepest,
  'titleBar.inactiveForeground': fg.subtle,
  'titleBar.border': alpha.hairline,
  'menu.background': bg.raised,
  'menu.foreground': fg.primary,
  'menu.border': alpha.hairlineStrong,
  'menu.selectionBackground': accent.purpleDeep,
  'menu.selectionForeground': '#FFFFFF',
  'menu.separatorBackground': alpha.hairlineStrong,
  'menubar.selectionBackground': alpha.hover,
  'menubar.selectionForeground': fg.primary,

  // ---- Command palette & notifications -------------------------------------
  'quickInput.background': bg.raised,
  'quickInput.foreground': fg.primary,
  'quickInputList.focusBackground': accent.purpleDeep,
  'quickInputList.focusForeground': '#FFFFFF',
  'quickInputTitle.background': bg.raisedHigh,
  'pickerGroup.border': alpha.hairlineStrong,
  'pickerGroup.foreground': accent.gold,
  'keybindingLabel.background': bg.raisedHigh,
  'keybindingLabel.foreground': fg.primary,
  'keybindingLabel.border': alpha.hairlineStrong,
  'keybindingLabel.bottomBorder': alpha.hairlineStrong,
  'notificationCenter.border': alpha.hairlineStrong,
  'notificationCenterHeader.background': bg.raisedHigh,
  'notificationCenterHeader.foreground': fg.primary,
  'notifications.background': bg.raised,
  'notifications.foreground': fg.primary,
  'notifications.border': alpha.hairlineStrong,
  'notificationLink.foreground': syntax.cyan,
  'notificationsErrorIcon.foreground': status.error,
  'notificationsWarningIcon.foreground': status.warning,
  'notificationsInfoIcon.foreground': status.info,

  // ---- Breadcrumbs ---------------------------------------------------------
  'breadcrumb.background': bg.editor,
  'breadcrumb.foreground': fg.muted,
  'breadcrumb.focusForeground': fg.primary,
  'breadcrumb.activeSelectionForeground': accent.gold,
  'breadcrumbPicker.background': bg.raised,

  // ---- Git & SCM -----------------------------------------------------------
  'gitDecoration.addedResourceForeground': git.added,
  'gitDecoration.modifiedResourceForeground': git.modified,
  'gitDecoration.deletedResourceForeground': git.deleted,
  'gitDecoration.untrackedResourceForeground': git.untracked,
  'gitDecoration.ignoredResourceForeground': git.ignored,
  'gitDecoration.conflictingResourceForeground': git.conflict,
  'gitDecoration.stageModifiedResourceForeground': git.modified,
  'gitDecoration.stageDeletedResourceForeground': git.deleted,
  'gitDecoration.submoduleResourceForeground': git.submodule,

  // ---- Debug ---------------------------------------------------------------
  'debugToolBar.background': bg.raised,
  'debugToolBar.border': alpha.hairlineStrong,
  'debugIcon.breakpointForeground': status.error,
  'debugIcon.breakpointDisabledForeground': fg.subtle,
  'debugIcon.startForeground': syntax.sage,
  'debugIcon.pauseForeground': accent.gold,
  'debugIcon.stopForeground': status.error,
  'debugIcon.continueForeground': syntax.sage,
  'debugIcon.restartForeground': syntax.sage,
  'debugIcon.stepOverForeground': syntax.cyan,
  'debugIcon.stepIntoForeground': syntax.cyan,
  'debugIcon.stepOutForeground': syntax.cyan,
  'debugIcon.stepBackForeground': syntax.cyan,
  'debugIcon.disconnectForeground': status.error,
  'debugConsole.infoForeground': status.info,
  'debugConsole.warningForeground': status.warning,
  'debugConsole.errorForeground': status.error,
  'debugConsole.sourceForeground': fg.muted,
  'debugConsoleInputIcon.foreground': accent.gold,
  'debugExceptionWidget.background': '#3D1A22',
  'debugExceptionWidget.border': status.error,
  'editor.stackFrameHighlightBackground': `${accent.gold}26`,
  'editor.focusedStackFrameHighlightBackground': `${syntax.sage}26`,

  // ---- Testing -------------------------------------------------------------
  'testing.iconPassed': syntax.sage,
  'testing.iconFailed': status.error,
  'testing.iconErrored': status.error,
  'testing.iconSkipped': fg.subtle,
  'testing.iconQueued': accent.gold,
  'testing.iconUnset': fg.subtle,
  'testing.runAction': syntax.sage,

  // ---- Settings ------------------------------------------------------------
  'settings.headerForeground': fg.primary,
  'settings.modifiedItemIndicator': accent.gold,
  'settings.dropdownBackground': bg.raised,
  'settings.dropdownBorder': alpha.hairlineStrong,
  'settings.checkboxBackground': bg.raised,
  'settings.checkboxBorder': alpha.hairlineStrong,
  'settings.textInputBackground': bg.raised,
  'settings.textInputBorder': alpha.hairlineStrong,
  'settings.numberInputBackground': bg.raised,
  'settings.numberInputBorder': alpha.hairlineStrong,
  'settings.focusedRowBackground': alpha.hover,

  // ---- Charts & minimap ----------------------------------------------------
  'charts.foreground': fg.primary,
  'charts.lines': alpha.hairlineStrong,
  'charts.red': status.error,
  'charts.blue': status.info,
  'charts.yellow': accent.gold,
  'charts.orange': syntax.peach,
  'charts.green': syntax.sage,
  'charts.purple': syntax.violet,
  'minimap.background': bg.editor,
  'minimap.findMatchHighlight': `${accent.gold}99`,
  'minimap.selectionHighlight': `${accent.purple}99`,
  'minimap.errorHighlight': status.error,
  'minimap.warningHighlight': status.warning,
  'minimapSlider.background': alpha.scrollbar,
  'minimapSlider.hoverBackground': alpha.scrollbarHover,
  'minimapSlider.activeBackground': alpha.scrollbarActive,
  'minimapGutter.addedBackground': git.added,
  'minimapGutter.modifiedBackground': git.modified,
  'minimapGutter.deletedBackground': git.deleted,

  // ---- Welcome & extensions ------------------------------------------------
  'welcomePage.tileBackground': bg.raised,
  'welcomePage.tileHoverBackground': bg.raisedHigh,
  'welcomePage.progress.background': bg.raisedHigh,
  'welcomePage.progress.foreground': accent.gold,
  'walkThrough.embeddedEditorBackground': bg.deep,
  'extensionButton.prominentBackground': accent.gold,
  'extensionButton.prominentForeground': bg.deepest,
  'extensionButton.prominentHoverBackground': '#F7D670',
  'extensionBadge.remoteBackground': accent.purpleDeep,
  'extensionBadge.remoteForeground': '#FFFFFF',
  'extensionIcon.starForeground': accent.gold,
  'extensionIcon.verifiedForeground': syntax.cyan,
  'extensionIcon.preReleaseForeground': syntax.violet,

  // ---- Notebooks -----------------------------------------------------------
  'notebook.cellBorderColor': alpha.hairlineStrong,
  'notebook.cellEditorBackground': bg.deep,
  'notebook.focusedCellBorder': accent.purple,
  'notebook.selectedCellBackground': alpha.hover,
  'notebook.outputContainerBackgroundColor': bg.deep,
};

/**
 * Token colors, organized by role rather than by language. A small set of
 * scope-level rules covers far more real code than the previous per-language
 * sprawl, and keeps every language on the same palette.
 */
const tokenColors = [
  {
    name: 'Comment',
    scope: ['comment', 'punctuation.definition.comment', 'string.comment'],
    settings: { foreground: syntax.comment, fontStyle: 'italic' },
  },
  {
    name: 'String',
    scope: ['string', 'string.quoted', 'string.template', 'meta.attribute-selector'],
    settings: { foreground: syntax.sage },
  },
  {
    name: 'String punctuation',
    scope: ['punctuation.definition.string'],
    settings: { foreground: syntax.sage },
  },
  {
    name: 'Template expression punctuation',
    scope: [
      'punctuation.definition.template-expression',
      'punctuation.section.embedded',
      'meta.embedded',
    ],
    settings: { foreground: syntax.violet },
  },
  {
    name: 'Number, constant, language literal',
    scope: [
      'constant.numeric',
      'constant.language',
      'constant.character',
      'constant.other',
      'constant.character.escape',
      'keyword.other.unit',
      'variable.other.constant',
      'support.constant',
    ],
    settings: { foreground: syntax.rose },
  },
  {
    name: 'Keyword',
    scope: ['keyword', 'keyword.control', 'keyword.other', 'punctuation.definition.keyword'],
    settings: { foreground: syntax.violet },
  },
  {
    name: 'Storage and modifiers',
    scope: ['storage', 'storage.type', 'storage.modifier', 'keyword.operator.new'],
    settings: { foreground: syntax.violet },
  },
  {
    name: 'Operator',
    scope: ['keyword.operator', 'keyword.operator.expression', 'keyword.operator.logical'],
    settings: { foreground: syntax.punctuation },
  },
  {
    name: 'Punctuation',
    scope: [
      'punctuation',
      'punctuation.separator',
      'punctuation.terminator',
      'punctuation.accessor',
      'meta.brace',
    ],
    settings: { foreground: syntax.punctuation },
  },
  {
    name: 'Function and method',
    scope: [
      'entity.name.function',
      'support.function',
      'meta.function-call',
      'meta.function-call.generic',
      'variable.function',
      'keyword.other.special-method',
    ],
    settings: { foreground: syntax.cyan },
  },
  {
    name: 'Function declaration name',
    scope: ['entity.name.function.member', 'meta.definition.method entity.name.function'],
    settings: { foreground: syntax.cyan },
  },
  {
    name: 'Class, type, interface, enum',
    scope: [
      'entity.name.type',
      'entity.name.class',
      'entity.name.namespace',
      'entity.name.scope-resolution',
      'entity.other.inherited-class',
      'support.class',
      'support.type',
      'meta.type.annotation',
    ],
    settings: { foreground: syntax.gold },
  },
  {
    name: 'Decorator and annotation',
    scope: ['meta.decorator', 'entity.name.function.decorator', 'punctuation.decorator'],
    settings: { foreground: syntax.gold, fontStyle: 'italic' },
  },
  {
    name: 'Variable',
    scope: ['variable', 'variable.other', 'variable.other.readwrite', 'meta.definition.variable'],
    settings: { foreground: syntax.lavender },
  },
  {
    name: 'Object property',
    scope: [
      'variable.other.property',
      'support.variable.property',
      'meta.object-literal.key',
      'variable.object.property',
    ],
    settings: { foreground: syntax.lavender },
  },
  {
    name: 'Parameter',
    scope: ['variable.parameter', 'meta.parameter'],
    settings: { foreground: syntax.peach },
  },
  {
    name: 'Language variable (this, self, super)',
    scope: ['variable.language', 'variable.language.this', 'keyword.other.this'],
    settings: { foreground: syntax.rose, fontStyle: 'italic' },
  },
  {
    name: 'HTML/XML tag',
    scope: ['entity.name.tag', 'meta.tag', 'punctuation.definition.tag'],
    settings: { foreground: syntax.rose },
  },
  {
    name: 'HTML/XML attribute',
    scope: ['entity.other.attribute-name', 'meta.attribute'],
    settings: { foreground: syntax.gold, fontStyle: 'italic' },
  },
  {
    name: 'CSS selector',
    scope: [
      'entity.name.tag.css',
      'entity.other.attribute-name.class.css',
      'entity.other.attribute-name.id.css',
      'entity.other.attribute-name.pseudo-class.css',
      'entity.other.attribute-name.pseudo-element.css',
    ],
    settings: { foreground: syntax.gold },
  },
  {
    name: 'CSS property name',
    scope: ['support.type.property-name.css', 'support.type.vendored.property-name'],
    settings: { foreground: syntax.cyan },
  },
  {
    name: 'CSS property value',
    scope: ['support.constant.property-value', 'meta.property-value'],
    settings: { foreground: syntax.rose },
  },
  {
    name: 'JSON key',
    scope: ['support.type.property-name.json', 'meta.structure.dictionary.key.json'],
    settings: { foreground: syntax.cyan },
  },
  {
    name: 'Regular expression',
    scope: ['string.regexp', 'constant.other.character-class.regexp'],
    settings: { foreground: syntax.peach },
  },
  {
    name: 'Regular expression operator',
    scope: [
      'keyword.operator.quantifier.regexp',
      'keyword.control.anchor.regexp',
      'punctuation.definition.group.regexp',
    ],
    settings: { foreground: syntax.violet },
  },
  {
    name: 'Module and import',
    scope: ['support.module', 'entity.name.type.module', 'keyword.control.import'],
    settings: { foreground: syntax.violet },
  },
  {
    name: 'Markdown heading',
    scope: ['markup.heading', 'entity.name.section'],
    settings: { foreground: accent.gold, fontStyle: 'bold' },
  },
  { name: 'Markdown bold', scope: ['markup.bold'], settings: { foreground: syntax.gold, fontStyle: 'bold' } },
  { name: 'Markdown italic', scope: ['markup.italic'], settings: { foreground: syntax.violet, fontStyle: 'italic' } },
  { name: 'Markdown strikethrough', scope: ['markup.strikethrough'], settings: { fontStyle: 'strikethrough' } },
  { name: 'Markdown quote', scope: ['markup.quote'], settings: { foreground: syntax.comment, fontStyle: 'italic' } },
  { name: 'Markdown list', scope: ['markup.list', 'beginning.punctuation.definition.list'], settings: { foreground: syntax.rose } },
  { name: 'Markdown code', scope: ['markup.inline.raw', 'markup.fenced_code', 'markup.raw'], settings: { foreground: syntax.sage } },
  {
    name: 'Markdown link',
    scope: ['markup.underline.link', 'string.other.link', 'constant.other.reference.link'],
    settings: { foreground: syntax.cyan, fontStyle: 'underline' },
  },
  { name: 'Diff inserted', scope: ['markup.inserted'], settings: { foreground: git.added } },
  { name: 'Diff deleted', scope: ['markup.deleted'], settings: { foreground: git.deleted } },
  { name: 'Diff changed', scope: ['markup.changed'], settings: { foreground: git.modified } },
  { name: 'Diff header', scope: ['meta.diff.header', 'meta.diff.range'], settings: { foreground: syntax.violet } },
  {
    name: 'Invalid',
    scope: ['invalid', 'invalid.illegal'],
    settings: { foreground: status.error },
  },
  {
    name: 'Deprecated',
    scope: ['invalid.deprecated'],
    settings: { foreground: status.warning, fontStyle: 'strikethrough' },
  },
  {
    name: 'YAML/TOML key',
    scope: ['entity.name.tag.yaml', 'support.type.property-name.toml', 'entity.name.tag.toml'],
    settings: { foreground: syntax.cyan },
  },
  {
    name: 'Shell built-in and command',
    scope: ['support.function.builtin.shell', 'entity.name.command.shell'],
    settings: { foreground: syntax.cyan },
  },
  {
    name: 'Escape and placeholder',
    scope: ['constant.character.format.placeholder', 'constant.other.placeholder'],
    settings: { foreground: syntax.peach },
  },
];

/** Semantic tokens, which take precedence over TextMate scopes where a language server supplies them. */
const semanticTokenColors = {
  namespace: syntax.gold,
  class: syntax.gold,
  interface: syntax.gold,
  type: syntax.gold,
  enum: syntax.gold,
  typeParameter: syntax.gold,
  struct: syntax.gold,
  function: syntax.cyan,
  method: syntax.cyan,
  macro: syntax.cyan,
  event: syntax.cyan,
  variable: syntax.lavender,
  parameter: syntax.peach,
  property: syntax.lavender,
  enumMember: syntax.rose,
  keyword: syntax.violet,
  modifier: syntax.violet,
  operator: syntax.punctuation,
  string: syntax.sage,
  number: syntax.rose,
  regexp: syntax.peach,
  comment: { foreground: syntax.comment, fontStyle: 'italic' },
  decorator: { foreground: syntax.gold, fontStyle: 'italic' },
  'variable.constant': syntax.rose,
  'variable.defaultLibrary': syntax.gold,
  'variable.readonly': syntax.lavender,
  'property.declaration': syntax.lavender,
  'function.defaultLibrary': syntax.cyan,
  'class.defaultLibrary': syntax.gold,
  'variable.deprecated': { fontStyle: 'strikethrough' },
  'function.deprecated': { fontStyle: 'strikethrough' },
};

const theme = {
  $schema: 'vscode://schemas/color-theme',
  name: 'King',
  type: 'dark',
  semanticHighlighting: true,
  semanticTokenColors,
  tokenColors,
  colors,
};

writeFileSync(OUT, `${JSON.stringify(theme, null, 2)}\n`, 'utf8');

console.log(
  `Wrote ${OUT}\n  ${Object.keys(colors).length} workbench colors\n` +
    `  ${tokenColors.length} token color rules\n` +
    `  ${Object.keys(semanticTokenColors).length} semantic token rules`
);
